'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Languages
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GHOSTbackup.Strings", GetType(Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup successfully deleted..
        '''</summary>
        Friend Shared ReadOnly Property banner_backup_deleted() As String
            Get
                Return ResourceManager.GetString("banner_backup_deleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backups successfully deleted..
        '''</summary>
        Friend Shared ReadOnly Property banner_backup_deleted_all() As String
            Get
                Return ResourceManager.GetString("banner_backup_deleted_all", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup folder doesn&apos;t exist..
        '''</summary>
        Friend Shared ReadOnly Property banner_backup_folder_404_info() As String
            Get
                Return ResourceManager.GetString("banner_backup_folder_404_info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup folder no longer exists..
        '''</summary>
        Friend Shared ReadOnly Property banner_backup_folder_deleted() As String
            Get
                Return ResourceManager.GetString("banner_backup_folder_deleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup successfully restored..
        '''</summary>
        Friend Shared ReadOnly Property banner_backup_restored() As String
            Get
                Return ResourceManager.GetString("banner_backup_restored", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occurred while retrieving the list of backups..
        '''</summary>
        Friend Shared ReadOnly Property banner_backups_table_retrieve_error() As String
            Get
                Return ResourceManager.GetString("banner_backups_table_retrieve_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The selected Wildlands executable could not be found..
        '''</summary>
        Friend Shared ReadOnly Property banner_customexe_404_error() As String
            Get
                Return ResourceManager.GetString("banner_customexe_404_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The current folder does not exist..
        '''</summary>
        Friend Shared ReadOnly Property banner_folder_404_info() As String
            Get
                Return ResourceManager.GetString("banner_folder_404_info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must launch Wildlands before starting the backup process..
        '''</summary>
        Friend Shared ReadOnly Property banner_launch_before_backup_info() As String
            Get
                Return ResourceManager.GetString("banner_launch_before_backup_info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Logging to file disabled due to an error..
        '''</summary>
        Friend Shared ReadOnly Property banner_log_error() As String
            Get
                Return ResourceManager.GetString("banner_log_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The event log file does not exist..
        '''</summary>
        Friend Shared ReadOnly Property banner_log_file_404_info() As String
            Get
                Return ResourceManager.GetString("banner_log_file_404_info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The selected backup no longer exists..
        '''</summary>
        Friend Shared ReadOnly Property banner_manage_backup_folder_404_info() As String
            Get
                Return ResourceManager.GetString("banner_manage_backup_folder_404_info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must quit Wildlands before restoring a backup..
        '''</summary>
        Friend Shared ReadOnly Property banner_quit_before_restore_info() As String
            Get
                Return ResourceManager.GetString("banner_quit_before_restore_info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wildlands save games folder doesn&apos;t exist..
        '''</summary>
        Friend Shared ReadOnly Property banner_savegames_folder_404_info() As String
            Get
                Return ResourceManager.GetString("banner_savegames_folder_404_info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wildlands save games folder no longer exists..
        '''</summary>
        Friend Shared ReadOnly Property banner_savegames_folder_deleted() As String
            Get
                Return ResourceManager.GetString("banner_savegames_folder_deleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must specify both save games and backup folders..
        '''</summary>
        Friend Shared ReadOnly Property banner_specify_folders_info() As String
            Get
                Return ResourceManager.GetString("banner_specify_folders_info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to get latest backup timestamp. Please check the logs for more details..
        '''</summary>
        Friend Shared ReadOnly Property banner_timestamp_error() As String
            Get
                Return ResourceManager.GetString("banner_timestamp_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to check for updates. Please check the logs for more details..
        '''</summary>
        Friend Shared ReadOnly Property banner_update_error() As String
            Get
                Return ResourceManager.GetString("banner_update_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uplay is not installed..
        '''</summary>
        Friend Shared ReadOnly Property banner_uplay_not_installed() As String
            Get
                Return ResourceManager.GetString("banner_uplay_not_installed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select where you want to backup your save files to. Every backup will create a new &quot;yyyyMMdd HHmm&quot; subfolder..
        '''</summary>
        Friend Shared ReadOnly Property dialog_browse_backup_desc() As String
            Get
                Return ResourceManager.GetString("dialog_browse_backup_desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wildlands executable (GRW.exe)|{0}.
        '''</summary>
        Friend Shared ReadOnly Property dialog_browse_customexe_filter() As String
            Get
                Return ResourceManager.GetString("dialog_browse_customexe_filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Wildlands executable..
        '''</summary>
        Friend Shared ReadOnly Property dialog_browse_customexe_title() As String
            Get
                Return ResourceManager.GetString("dialog_browse_customexe_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select where you want to save the event log file to..
        '''</summary>
        Friend Shared ReadOnly Property dialog_browse_log_destination_desc() As String
            Get
                Return ResourceManager.GetString("dialog_browse_log_destination_desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Wildlands save games folder. If you don&apos;t know where it is, please consult PC Gaming Wiki..
        '''</summary>
        Friend Shared ReadOnly Property dialog_browse_savegames_desc() As String
            Get
                Return ResourceManager.GetString("dialog_browse_savegames_desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text file|{0}|Log file|{1}.
        '''</summary>
        Friend Shared ReadOnly Property dialog_save_log_filter() As String
            Get
                Return ResourceManager.GetString("dialog_save_log_filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save log as....
        '''</summary>
        Friend Shared ReadOnly Property dialog_save_log_title() As String
            Get
                Return ResourceManager.GetString("dialog_save_log_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup doesn&apos;t exist.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_backup_404_title() As String
            Get
                Return ResourceManager.GetString("msgbox_backup_404_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 Deleting a backup will free up space on your backup location. The backup folder &lt;0&gt; and all save files inside of it will be {\b PERMANENTLY DELETED.}\line\line {\b THIS CANNOT BE UNDONE. ARE YOU SURE YOU WANT TO PROCEED?}}.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_backup_delete() As String
            Get
                Return ResourceManager.GetString("msgbox_backup_delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 Deleting all backups will free up space on your backup location and will prevent you from restoring save files. All backups inside &lt;0&gt; will be {\b PERMANENTLY DELETED.}\line\line {\b THIS CANNOT BE UNDONE. ARE YOU SURE YOU WANT TO PROCEED?}}.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_backup_delete_all() As String
            Get
                Return ResourceManager.GetString("msgbox_backup_delete_all", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 Deleting the only backup will prevent you from restoring save files. The backup folder &lt;0&gt; and all save files inside of it will be {\b PERMANENTLY DELETED.}\line\line {\b THIS CANNOT BE UNDONE. ARE YOU SURE YOU WANT TO PROCEED?}}.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_backup_delete_latest() As String
            Get
                Return ResourceManager.GetString("msgbox_backup_delete_latest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup deletion.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_backup_delete_title() As String
            Get
                Return ResourceManager.GetString("msgbox_backup_delete_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 The backup process has been {\b interrupted due to an error.} Please check the logs for more details.}.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_backup_error() As String
            Get
                Return ResourceManager.GetString("msgbox_backup_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup interrupted.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_backup_error_title() As String
            Get
                Return ResourceManager.GetString("msgbox_backup_error_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 Restoring a backup will copy the save files over from the backup folder: &lt;0&gt;\line\line and will {\b OVERWRITE} the existing save files inside the game folder: &lt;1&gt;\line\line {\b THIS CANNOT BE UNDONE. ARE YOU SURE YOU WANT TO PROCEED?}}.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_backup_restore() As String
            Get
                Return ResourceManager.GetString("msgbox_backup_restore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 You chose to restore the second-to-last backup but {\b it doesn&apos;t exist.} Do you want to restore the latest backup instead? This will copy the save files over from the backup folder: &lt;0&gt;\line\line And will {\b OVERWRITE} the existing save files inside the game folder: &lt;1&gt;\line\line {\b THIS CANNOT BE UNDONE. ARE YOU SURE YOU WANT TO PROCEED?}}.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_backup_restore_no_sectolast() As String
            Get
                Return ResourceManager.GetString("msgbox_backup_restore_no_sectolast", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup restore.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_backup_restore_title() As String
            Get
                Return ResourceManager.GetString("msgbox_backup_restore_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_btn_cancel() As String
            Get
                Return ResourceManager.GetString("msgbox_btn_cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_btn_no() As String
            Get
                Return ResourceManager.GetString("msgbox_btn_no", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_btn_ok() As String
            Get
                Return ResourceManager.GetString("msgbox_btn_ok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yes.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_btn_yes() As String
            Get
                Return ResourceManager.GetString("msgbox_btn_yes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 Are you sure you want to {\b interrupt the backup process?}}.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_confirm_backup_interruption() As String
            Get
                Return ResourceManager.GetString("msgbox_confirm_backup_interruption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup interruption.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_confirm_backup_interruption_title() As String
            Get
                Return ResourceManager.GetString("msgbox_confirm_backup_interruption_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 The backup process is still running. Do you want to {\b interrupt it and exit?}}.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_confirm_exit() As String
            Get
                Return ResourceManager.GetString("msgbox_confirm_exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm exit.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_confirm_exit_title() As String
            Get
                Return ResourceManager.GetString("msgbox_confirm_exit_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 {\b An error prevented} GHOST Buster from deleting the backup folder. Please check the logs for more details.}.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_delete_all_error() As String
            Get
                Return ResourceManager.GetString("msgbox_delete_all_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 {\b An error prevented} GHOST Buster from deleting the selected backup folder. Please check the logs for more details.}.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_delete_error() As String
            Get
                Return ResourceManager.GetString("msgbox_delete_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deletion failed.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_delete_error_title() As String
            Get
                Return ResourceManager.GetString("msgbox_delete_error_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 &quot;&lt;0&gt;&quot; setting has been {\b disabled because an error occurred} while trying to parse Uplay settings file. \line\line Make sure to {\b DISABLE} cloud save synchronization from Uplay (Settings -&gt; Untick &quot;Enable cloud save synchronization for supported games&quot;) before launching Wildlands, otherwise the restored save games will be {\b OVERWRITTEN} with the old ones from the cloud!}.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_disable_sync_error() As String
            Get
                Return ResourceManager.GetString("msgbox_disable_sync_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 The current {\b backup folder is empty.} Backup at least once and try again.}.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_empty_backup_folder() As String
            Get
                Return ResourceManager.GetString("msgbox_empty_backup_folder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No backup found.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_empty_backup_folder_title() As String
            Get
                Return ResourceManager.GetString("msgbox_empty_backup_folder_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 {\b An error occurred} while trying to parse Uplay settings file. Please re-enable cloud save synchronization manually from Uplay (Settings -&gt; Tick &quot;Enable cloud save synchronization for supported games&quot;).}.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_enable_sync_error() As String
            Get
                Return ResourceManager.GetString("msgbox_enable_sync_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 GHOST Buster was unable to enable cloud save synchronization {\b because Uplay is running.} Please re-enable it manually from Uplay (Settings -&gt; Tick &quot;Enable cloud save synchronization for supported games&quot;).}.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_enable_sync_uplay_error() As String
            Get
                Return ResourceManager.GetString("msgbox_enable_sync_uplay_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot enable cloud sync.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_enable_sync_uplay_error_title() As String
            Get
                Return ResourceManager.GetString("msgbox_enable_sync_uplay_error_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 The current {\b backup folder doesn&apos;t contain any backup.} Backup at least once and try again.}.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_invalid_backup_folder() As String
            Get
                Return ResourceManager.GetString("msgbox_invalid_backup_folder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No backup found.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_invalid_backup_folder_title() As String
            Get
                Return ResourceManager.GetString("msgbox_invalid_backup_folder_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parsing failed.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_parsing_error_title() As String
            Get
                Return ResourceManager.GetString("msgbox_parsing_error_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 You must {\b quit Uplay before restoring a backup} because you chose to let GHOST Buster disable Uplay cloud save synchronization for you.}.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_quit_before_restore_sync() As String
            Get
                Return ResourceManager.GetString("msgbox_quit_before_restore_sync", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot restore.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_quit_before_restore_sync_title() As String
            Get
                Return ResourceManager.GetString("msgbox_quit_before_restore_sync_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 The restore process has been {\b interrupted due to an error.} Please check the logs for more details.}.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_restore_error() As String
            Get
                Return ResourceManager.GetString("msgbox_restore_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restore failed.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_restore_error_title() As String
            Get
                Return ResourceManager.GetString("msgbox_restore_error_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 A newer version of GHOST Buster is available. Do you want to {\b visit the download page} now?}.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_update_available() As String
            Get
                Return ResourceManager.GetString("msgbox_update_available", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update available.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_update_available_title() As String
            Get
                Return ResourceManager.GetString("msgbox_update_available_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 Wildlands {\b has been closed or crashed}, as a result the backup process has been interrupted.}.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_wildlands_closed_crashed() As String
            Get
                Return ResourceManager.GetString("msgbox_wildlands_closed_crashed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wildlands is no longer running.
        '''</summary>
        Friend Shared ReadOnly Property msgbox_wildlands_closed_crashed_title() As String
            Get
                Return ResourceManager.GetString("msgbox_wildlands_closed_crashed_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup complete..
        '''</summary>
        Friend Shared ReadOnly Property notification_msg_backup_complete() As String
            Get
                Return ResourceManager.GetString("notification_msg_backup_complete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup interrupted because an error occurred..
        '''</summary>
        Friend Shared ReadOnly Property notification_msg_backup_error() As String
            Get
                Return ResourceManager.GetString("notification_msg_backup_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Performed first backup..
        '''</summary>
        Friend Shared ReadOnly Property notification_msg_first_backup() As String
            Get
                Return ResourceManager.GetString("notification_msg_first_backup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter a value between {0} and {1}..
        '''</summary>
        Friend Shared ReadOnly Property tooltip_backup_frequency() As String
            Get
                Return ResourceManager.GetString("tooltip_backup_frequency", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If checked, GHOST Buster will display a notification at the edge of the screen about backups..
        '''</summary>
        Friend Shared ReadOnly Property tooltip_backup_notification() As String
            Get
                Return ResourceManager.GetString("tooltip_backup_notification", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If checked, GHOST Buster will show a confirmation dialog before interrupting the backup process..
        '''</summary>
        Friend Shared ReadOnly Property tooltip_confirm_backup_interruption() As String
            Get
                Return ResourceManager.GetString("tooltip_confirm_backup_interruption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If checked, GHOST Buster will show a confirmation dialog before exiting when the backup process is running..
        '''</summary>
        Friend Shared ReadOnly Property tooltip_confirm_exit() As String
            Get
                Return ResourceManager.GetString("tooltip_confirm_exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If checked, GHOST Buster will restore its position on the screen when reopened..
        '''</summary>
        Friend Shared ReadOnly Property tooltip_coordinates() As String
            Get
                Return ResourceManager.GetString("tooltip_coordinates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If checked, GHOST Buster will disable Uplay cloud save synchronization before restoring a backup..
        '''</summary>
        Friend Shared ReadOnly Property tooltip_disable_sync() As String
            Get
                Return ResourceManager.GetString("tooltip_disable_sync", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If checked, GHOST Buster will enable  Uplay cloud save synchronization again before  quitting..
        '''</summary>
        Friend Shared ReadOnly Property tooltip_enable_sync() As String
            Get
                Return ResourceManager.GetString("tooltip_enable_sync", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If checked, GHOST Buster will check if the current version is up to date when opening..
        '''</summary>
        Friend Shared ReadOnly Property tooltip_updates() As String
            Get
                Return ResourceManager.GetString("tooltip_updates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Launch Uplay..
        '''</summary>
        Friend Shared ReadOnly Property tooltip_uplay() As String
            Get
                Return ResourceManager.GetString("tooltip_uplay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About.
        '''</summary>
        Friend Shared ReadOnly Property topmenu_about() As String
            Get
                Return ResourceManager.GetString("topmenu_about", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Logs.
        '''</summary>
        Friend Shared ReadOnly Property topmenu_logs() As String
            Get
                Return ResourceManager.GetString("topmenu_logs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GHOST Buster v{0}\nCopyright (c) 2019 - 2020 Alberto Strappazzon\nThis software is licensed under the MIT license.\n\nThis software uses assets from Tom Clancy&apos;s Ghost Recon(R) Wildlands\nCopyright (c) Ubisoft Entertainment. All Rights Reserved.\n\nSome icons are taken from Icons8 (https://icons8.com)..
        '''</summary>
        Friend Shared ReadOnly Property ui_about_about() As String
            Get
                Return ResourceManager.GetString("ui_about_about", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Changelog.
        '''</summary>
        Friend Shared ReadOnly Property ui_about_changelog() As String
            Get
                Return ResourceManager.GetString("ui_about_changelog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Support.
        '''</summary>
        Friend Shared ReadOnly Property ui_about_issues() As String
            Get
                Return ResourceManager.GetString("ui_about_issues", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to License.
        '''</summary>
        Friend Shared ReadOnly Property ui_about_legal() As String
            Get
                Return ResourceManager.GetString("ui_about_legal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Official Website.
        '''</summary>
        Friend Shared ReadOnly Property ui_about_www() As String
            Get
                Return ResourceManager.GetString("ui_about_www", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Browse....
        '''</summary>
        Friend Shared ReadOnly Property ui_btn_browse() As String
            Get
                Return ResourceManager.GetString("ui_btn_browse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open.
        '''</summary>
        Friend Shared ReadOnly Property ui_btn_open() As String
            Get
                Return ResourceManager.GetString("ui_btn_open", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Folder.
        '''</summary>
        Friend Shared ReadOnly Property ui_btn_open_folder() As String
            Get
                Return ResourceManager.GetString("ui_btn_open_folder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup location.
        '''</summary>
        Friend Shared ReadOnly Property ui_folders_backup() As String
            Get
                Return ResourceManager.GetString("ui_folders_backup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wildlands save games folder.
        '''</summary>
        Friend Shared ReadOnly Property ui_folders_wildlands() As String
            Get
                Return ResourceManager.GetString("ui_folders_wildlands", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy.
        '''</summary>
        Friend Shared ReadOnly Property ui_logs_context_copy() As String
            Get
                Return ResourceManager.GetString("ui_logs_context_copy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy the selected text to clipboard..
        '''</summary>
        Friend Shared ReadOnly Property ui_logs_context_copy_tooltip() As String
            Get
                Return ResourceManager.GetString("ui_logs_context_copy_tooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save log as....
        '''</summary>
        Friend Shared ReadOnly Property ui_logs_context_export() As String
            Get
                Return ResourceManager.GetString("ui_logs_context_export", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save all events to a log file..
        '''</summary>
        Friend Shared ReadOnly Property ui_logs_context_export_tooltip() As String
            Get
                Return ResourceManager.GetString("ui_logs_context_export_tooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select all.
        '''</summary>
        Friend Shared ReadOnly Property ui_logs_context_selectall() As String
            Get
                Return ResourceManager.GetString("ui_logs_context_selectall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select all the text..
        '''</summary>
        Friend Shared ReadOnly Property ui_logs_context_selectall_tooltip() As String
            Get
                Return ResourceManager.GetString("ui_logs_context_selectall_tooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backups.
        '''</summary>
        Friend Shared ReadOnly Property ui_manage() As String
            Get
                Return ResourceManager.GetString("ui_manage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend Shared ReadOnly Property ui_manage_context_delete() As String
            Get
                Return ResourceManager.GetString("ui_manage_context_delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete the selected backup..
        '''</summary>
        Friend Shared ReadOnly Property ui_manage_context_delete_tooltip() As String
            Get
                Return ResourceManager.GetString("ui_manage_context_delete_tooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete All.
        '''</summary>
        Friend Shared ReadOnly Property ui_manage_context_deleteall() As String
            Get
                Return ResourceManager.GetString("ui_manage_context_deleteall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete all backups..
        '''</summary>
        Friend Shared ReadOnly Property ui_manage_context_deleteall_tooltip() As String
            Get
                Return ResourceManager.GetString("ui_manage_context_deleteall_tooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show in Explorer.
        '''</summary>
        Friend Shared ReadOnly Property ui_manage_context_explorer() As String
            Get
                Return ResourceManager.GetString("ui_manage_context_explorer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open the selected backup folder in Windows Explorer..
        '''</summary>
        Friend Shared ReadOnly Property ui_manage_context_explorer_tooltip() As String
            Get
                Return ResourceManager.GetString("ui_manage_context_explorer_tooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Refresh.
        '''</summary>
        Friend Shared ReadOnly Property ui_manage_context_refresh() As String
            Get
                Return ResourceManager.GetString("ui_manage_context_refresh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Refresh the list of backups..
        '''</summary>
        Friend Shared ReadOnly Property ui_manage_context_refresh_tooltip() As String
            Get
                Return ResourceManager.GetString("ui_manage_context_refresh_tooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restore.
        '''</summary>
        Friend Shared ReadOnly Property ui_manage_context_restore() As String
            Get
                Return ResourceManager.GetString("ui_manage_context_restore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restore the selected backup..
        '''</summary>
        Friend Shared ReadOnly Property ui_manage_context_restore_tooltip() As String
            Get
                Return ResourceManager.GetString("ui_manage_context_restore_tooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Folder.
        '''</summary>
        Friend Shared ReadOnly Property ui_manage_table_column_folder() As String
            Get
                Return ResourceManager.GetString("ui_manage_table_column_folder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Size ({0}).
        '''</summary>
        Friend Shared ReadOnly Property ui_manage_table_column_size() As String
            Get
                Return ResourceManager.GetString("ui_manage_table_column_size", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Creation date.
        '''</summary>
        Friend Shared ReadOnly Property ui_manage_table_column_timestamp() As String
            Get
                Return ResourceManager.GetString("ui_manage_table_column_timestamp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Play Ghost Recon Wildlands.
        '''</summary>
        Friend Shared ReadOnly Property ui_play() As String
            Get
                Return ResourceManager.GetString("ui_play", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ghost Recon Wildlands is not installed.
        '''</summary>
        Friend Shared ReadOnly Property ui_play_disabled() As String
            Get
                Return ResourceManager.GetString("ui_play_disabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ghost Recon Wildlands not found.
        '''</summary>
        Friend Shared ReadOnly Property ui_play_disabled_404() As String
            Get
                Return ResourceManager.GetString("ui_play_disabled_404", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display notifications about backups.
        '''</summary>
        Friend Shared ReadOnly Property ui_settings_backup_notification() As String
            Get
                Return ResourceManager.GetString("ui_settings_backup_notification", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm backup interruption.
        '''</summary>
        Friend Shared ReadOnly Property ui_settings_confirm_backup_interruption() As String
            Get
                Return ResourceManager.GetString("ui_settings_confirm_backup_interruption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm exit when backup is running.
        '''</summary>
        Friend Shared ReadOnly Property ui_settings_confirm_exit() As String
            Get
                Return ResourceManager.GetString("ui_settings_confirm_exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remember window position.
        '''</summary>
        Friend Shared ReadOnly Property ui_settings_coordinates() As String
            Get
                Return ResourceManager.GetString("ui_settings_coordinates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disable Uplay cloud save synchronization on restore.
        '''</summary>
        Friend Shared ReadOnly Property ui_settings_disable_sync() As String
            Get
                Return ResourceManager.GetString("ui_settings_disable_sync", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enable Uplay cloud save synchronization on exit.
        '''</summary>
        Friend Shared ReadOnly Property ui_settings_enable_sync() As String
            Get
                Return ResourceManager.GetString("ui_settings_enable_sync", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Interface language:.
        '''</summary>
        Friend Shared ReadOnly Property ui_settings_lang_choice() As String
            Get
                Return ResourceManager.GetString("ui_settings_lang_choice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Write events to a log file.
        '''</summary>
        Friend Shared ReadOnly Property ui_settings_log_file() As String
            Get
                Return ResourceManager.GetString("ui_settings_log_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I&apos;m not using the Uplay version of Wildlands.
        '''</summary>
        Friend Shared ReadOnly Property ui_settings_nouplay() As String
            Get
                Return ResourceManager.GetString("ui_settings_nouplay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You&apos;ll need to restart GHOST Buster in order for the change to take effect..
        '''</summary>
        Friend Shared ReadOnly Property ui_settings_restart() As String
            Get
                Return ResourceManager.GetString("ui_settings_restart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check for updates on startup.
        '''</summary>
        Friend Shared ReadOnly Property ui_settings_updates() As String
            Get
                Return ResourceManager.GetString("ui_settings_updates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start\nBackup.
        '''</summary>
        Friend Shared ReadOnly Property ui_tasks_backup() As String
            Get
                Return ResourceManager.GetString("ui_tasks_backup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Latest.
        '''</summary>
        Friend Shared ReadOnly Property ui_tasks_dropdown_latest() As String
            Get
                Return ResourceManager.GetString("ui_tasks_dropdown_latest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Second-to-last.
        '''</summary>
        Friend Shared ReadOnly Property ui_tasks_dropdown_second() As String
            Get
                Return ResourceManager.GetString("ui_tasks_dropdown_second", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup frequency.
        '''</summary>
        Friend Shared ReadOnly Property ui_tasks_freq() As String
            Get
                Return ResourceManager.GetString("ui_tasks_freq", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to minutes..
        '''</summary>
        Friend Shared ReadOnly Property ui_tasks_freq_minutes() As String
            Get
                Return ResourceManager.GetString("ui_tasks_freq_minutes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Latest backup:\n.
        '''</summary>
        Friend Shared ReadOnly Property ui_tasks_latest() As String
            Get
                Return ResourceManager.GetString("ui_tasks_latest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Latest backup:\nError..
        '''</summary>
        Friend Shared ReadOnly Property ui_tasks_latest_error() As String
            Get
                Return ResourceManager.GetString("ui_tasks_latest_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Latest backup:\nPlease wait....
        '''</summary>
        Friend Shared ReadOnly Property ui_tasks_latest_loading() As String
            Get
                Return ResourceManager.GetString("ui_tasks_latest_loading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Latest backup:\nNone yet..
        '''</summary>
        Friend Shared ReadOnly Property ui_tasks_latest_none() As String
            Get
                Return ResourceManager.GetString("ui_tasks_latest_none", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restore\nBackup.
        '''</summary>
        Friend Shared ReadOnly Property ui_tasks_restore() As String
            Get
                Return ResourceManager.GetString("ui_tasks_restore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup to restore.
        '''</summary>
        Friend Shared ReadOnly Property ui_tasks_restore_choice() As String
            Get
                Return ResourceManager.GetString("ui_tasks_restore_choice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop\nBackup.
        '''</summary>
        Friend Shared ReadOnly Property ui_tasks_stop() As String
            Get
                Return ResourceManager.GetString("ui_tasks_stop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About.
        '''</summary>
        Friend Shared ReadOnly Property ui_title_about() As String
            Get
                Return ResourceManager.GetString("ui_title_about", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Folders.
        '''</summary>
        Friend Shared ReadOnly Property ui_title_folders() As String
            Get
                Return ResourceManager.GetString("ui_title_folders", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Logs.
        '''</summary>
        Friend Shared ReadOnly Property ui_title_logs() As String
            Get
                Return ResourceManager.GetString("ui_title_logs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Manage Backups.
        '''</summary>
        Friend Shared ReadOnly Property ui_title_manage() As String
            Get
                Return ResourceManager.GetString("ui_title_manage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settings.
        '''</summary>
        Friend Shared ReadOnly Property ui_title_settings() As String
            Get
                Return ResourceManager.GetString("ui_title_settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tasks.
        '''</summary>
        Friend Shared ReadOnly Property ui_title_tasks() As String
            Get
                Return ResourceManager.GetString("ui_title_tasks", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
