# Website
url: https://strappazzon.github.io
baseurl: "/GRW-GHOST-Buster"
title: "GHOST Buster - Ghost Recon Wildlands Backup Utility"
description: "Backup and restore Ghost Recon Wildlands save games"
name: "GHOST Buster"

# Custom directories
includes_dir: _components
layouts_dir: _templates

# Excluded files, folders
exclude:
  - README.md

# Markdown
markdown: kramdown

# Kramdown
# See: https://kramdown.gettalong.org/options.html
kramdown:
  html_to_native: true
  input: GFM
  # Disable smart quotes
  smart_quotes: "apos,apos,quot,quot"
  syntax_highlighter: rouge
  # See: https://rouge-ruby.github.io/docs/#configuration
  syntax_highlighter_opts: {}

# CSS
sass:
  sourcemap: development
  style: compressed
