name: Pull Request Labeler

on:
  pull_request_target:
    types:
      - opened
    branches:
      - master

jobs:
  triage:
    name: Label Pull Request
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
        continue-on-error: true
